---
# Copyright (C) 2020-2022 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: GPL-2.0-or-later

- name: Create directory for {{ sympa_robot.domain }} robot
  file:
    state: directory
    path: "{{ sympa_configuration_directory }}/{{ sympa_robot.domain }}"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: 0755

- name: Create list data directory for {{ sympa_robot.domain }} robot
  file:
    state: directory
    path: "{{ sympa_list_home_directory }}/{{ sympa_robot.domain }}"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: 0755

- name: Create archives' directory {{ sympa_robot.domain }} robot
  file:
    state: directory
    path: "{{ sympa_installation_directory }}/arc/{{ sympa_robot.domain }}"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: 0755

- name: Create {{ sympa_robot.domain }} robot configuration file
  template:
    src: robot.conf.j2
    dest: "{{ sympa_configuration_directory }}/{{ sympa_robot.domain }}/robot.conf"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    mode: 0644
  notify:
    - restart sympa
    - restart wwsympa

