---
# Copyright (C) 2020-2022 Stefan Hornburg (Racke) <racke@linuxia.de>
# SPDX-License-Identifier: GPL-2.0-or-later

- name: Install FCGI wrapper
  package:
    name: spawn-fcgi
  tags:
    - sympa
    - wwsympa

- name: Install multiwatch
  package:
    name: multiwatch
  tags:
    - sympa
    - wwsympa

- name: Create socket unit for WWSympa
  template:
    src: wwsympa.socket.j2
    dest: /etc/systemd/system/wwsympa.socket
    owner: root
    group: root
    mode: 0644
  register: wwsympa_socket_unit
  notify: restart wwsympa
  tags:
    - sympa
    - wwsympa

- name: Create service unit for WWSympa
  template:
    src: wwsympa.service.j2
    dest: /etc/systemd/system/wwsympa.service
    owner: root
    group: root
    mode: 0644
  register: wwsympa_service_unit
  notify: restart wwsympa
  tags:
    - sympa
    - wwsympa

- name: Reload systemd if necessary
  systemd:
    daemon_reload: yes
  when:
    - wwsympa_socket_unit.changed or wwsympa_service_unit.changed

- name: Ensure that WWSympa socket is enabled and started
  service:
    name: wwsympa.socket
    enabled: yes
    state: started
  tags:
    - sympa
    - wwsympa
